apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-server
  namespace: default
  labels:
    app: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1234
      containers:
      - name: server
        image: lubowsky/kafka-reader:v1
        env:
        - name: BROKERS
          value: "kafka-1:9092"
        - name: TOPIC
          value: "monitoring"
        - name: GROUP
          value: "monitoring-group"
        imagePullPolicy: Always

