apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: default
  labels:
    run: example-service
spec:
  ports:
  - port: 80
    targetPort: 8090
    protocol: TCP
    name: http
  selector:
    app: example
